## GRADIENT BOOSTING TECHNIQUES

#### lightbgm download

In [9]:
pip install lightgbm

Collecting lightgbmNote: you may need to restart the kernel to use updated packages.

  Downloading lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
      --------------------------------------- 0.0/1.4 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.4 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.4 MB 325.1 kB/s eta 0:00:05
     -- ------------------------------------- 0.1/1.4 MB 326.8 kB/s eta 0:00:04
     --- ------------------------------------ 0.1/1.4 MB 409.6 kB/s eta 0:00:04
     ---- ----------------------------------- 0.1/1.4 MB 472.1 kB/s eta 0:00:03
     ------ --------------------------------- 0.2/1.4 MB 625.1 kB/s eta 0:00:02
     -------- ------------------------------- 0.3/1.4 MB 654.2 kB/s eta 0:00:02
     --------- ------------------------------ 0.3/1.4 MB 748.1 kB/s eta 0:00:02
     ----------- ---------------------------- 0.4/1.4 MB 807.8 kB/s eta 0:00:02
     ----------- ---------------------------- 0.4/1.4 MB 807.8 kB/s eta 0:00:02
     ----------------- ---------------------- 0.6/1.4 MB 999.9 kB/s eta 0:00:01
     ------------------ --------------------- 0.6/1.4 MB 1.0 MB/s eta 0:00:01
     --------------------- ------------------ 0.7/1.4 MB 1.1 MB/s eta 0:00:01
     ---------------------- ----------------- 0.8/1.4 MB 1.1 MB/s eta 0:00:01
     ------------------------- -------------- 0.9/1.4 MB 1.1 MB/s eta 0:00:01
     ---------------------------- ----------- 1.0/1.4 MB 1.2 MB/s eta 0:00:01
     ----------------------------- ---------- 1.0/1.4 MB 1.2 MB/s eta 0:00:01
     ----------------------------- ---------- 1.0/1.4 MB 1.2 MB/s eta 0:00:01
     ---------------------------------- ----- 1.2/1.4 MB 1.2 MB/s eta 0:00:01
     ------------------------------------ --- 1.2/1.4 MB 1.2 MB/s eta 0:00:01
     -------------------------------------- - 1.3/1.4 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------  1.4/1.4 MB 1.2 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 1.2 MB/s eta 0:00:00
Requirement already satisfied: scipy in c:\users\parth\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (1.15.3)
Requirement already satisfied: numpy>=1.21.3 in c:\users\parth\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (2.2.6)
Requirement already satisfied: narwhals>=1.15 in c:\users\parth\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (2.22.1)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.7.0

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
     ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
     -------------------------------------- 0.0/101.7 MB 163.8 kB/s eta 0:10:21
     -------------------------------------- 0.1/101.7 MB 273.8 kB/s eta 0:06:12
     -------------------------------------- 0.1/101.7 MB 302.7 kB/s eta 0:05:36
     -------------------------------------- 0.1/101.7 MB 328.0 kB/s eta 0:05:10
     -------------------------------------- 0.1/101.7 MB 405.9 kB/s eta 0:04:11
     -------------------------------------- 0.2/101.7 MB 464.2 kB/s eta 0:03:39
     -------------------------------------- 0.2/101.7 MB 464.2 kB/s eta 0:03:39
     -------------------------------------- 0.2/101.7 MB 464.2 kB/s eta 0:03:39
     -------------------------------------- 0.3/101.7 MB 596.5 kB/s eta 0:02:50
     -------------------------------------- 0.3/101.7 MB 584.6 kB/s eta 0:02:54
     -------------------------------------- 0.4/101.7 MB 608.0 kB/s eta 0:02:47
     -------------------------------------- 0.5/101.7 MB 655.2 kB/s eta 0:02:35
     -------------------------------------- 0.5/101.7 MB 656.0 kB/s eta 0:02:35
     -------------------------------------- 0.5/101.7 MB 669.0 kB/s eta 0:02:32
     -------------------------------------- 0.5/101.7 MB 669.0 kB/s eta 0:02:32
     -------------------------------------- 0.5/101.7 MB 669.0 kB/s eta 0:02:32
     -------------------------------------- 0.6/101.7 MB 655.8 kB/s eta 0:02:35
     -------------------------------------- 0.6/101.7 MB 655.3 kB/s eta 0:02:35
     -------------------------------------- 0.7/101.7 MB 666.0 kB/s eta 0:02:32
     -------------------------------------- 0.7/101.7 MB 665.6 kB/s eta 0:02:32
     -------------------------------------- 0.7/101.7 MB 655.4 kB/s eta 0:02:35
     -------------------------------------- 0.7/101.7 MB 646.3 kB/s eta 0:02:37
     -------------------------------------- 0.7/101.7 MB 637.8 kB/s eta 0:02:39
     -------------------------------------- 0.7/101.7 MB 637.8 kB/s eta 0:02:39
     -------------------------------------- 0.8/101.7 MB 615.5 kB/s eta 0:02:44
     -------------------------------------- 0.8/101.7 MB 615.5 kB/s eta 0:02:44
     -------------------------------------- 0.8/101.7 MB 595.8 kB/s eta 0:02:50
     -------------------------------------- 0.8/101.7 MB 589.9 kB/s eta 0:02:51
     -------------------------------------- 0.9/101.7 MB 591.5 kB/s eta 0:02:51
     -------------------------------------- 0.9/101.7 MB 580.3 kB/s eta 0:02:54
     -------------------------------------- 0.9/101.7 MB 580.3 kB/s eta 0:02:54
     -------------------------------------- 0.9/101.7 MB 580.3 kB/s eta 0:02:54
     -------------------------------------- 0.9/101.7 MB 555.7 kB/s eta 0:03:02
     -------------------------------------- 0.9/101.7 MB 542.4 kB/s eta 0:03:06
     -------------------------------------- 1.0/101.7 MB 544.2 kB/s eta 0:03:06
     -------------------------------------- 1.0/101.7 MB 535.6 kB/s eta 0:03:09
     -------------------------------------- 1.0/101.7 MB 535.6 kB/s eta 0:03:09
     -------------------------------------- 1.0/101.7 MB 525.5 kB/s eta 0:03:12
     -------------------------------------- 1.0/101.7 MB 525.5 kB/s eta 0:03:12
     -------------------------------------- 1.0/101.7 MB 525.5 kB/s eta 0:03:12
     -------------------------------------- 1.1/101.7 MB 514.3 kB/s eta 0:03:16
     -------------------------------------- 1.1/101.7 MB 512.5 kB/s eta 0:03:17
     -------------------------------------- 1.1/101.7 MB 509.8 kB/s eta 0:03:18
     -------------------------------------- 1.1/101.7 MB 509.8 kB/s eta 0:03:18
     -------------------------------------- 1.1/101.7 MB 497.4 kB/s eta 0:03:23
     -------------------------------------- 1.1/101.7 MB 497.4 kB/s eta 0:03:23
     -------------------------------------- 1.1/101.7 MB 481.5 kB/s eta 0:03:29
     -------------------------------------- 1.1/101.7 MB 481.5 kB/s eta 0:03:29
     -------------------------------------- 1.1/101.7 MB 468.2 kB/s eta 0:03:35
     -------------------------------------- 1.1/101.7 MB 468.2 kB/s eta 0:03:35
     -------------------------------------- 1.1/101.7 MB 451.9 kB/s eta 0:03:43
     -------------------------------------- 1.1/101.7 MB 451.9 kB/s eta 0:03:43
     -------------------------------------- 1.2/101.7 MB 446.2 kB/s eta 0:03:46
     -------------------------------------- 1.2/101.7 MB 446.2 kB/s eta 0:03:46
     -------------------------------------- 1.2/101.7 MB 446.2 kB/s eta 0:03:46
     -------------------------------------- 1.2/101.7 MB 446.2 kB/s eta 0:03:46
     -------------------------------------- 1.2/101.7 MB 424.7 kB/s eta 0:03:57
     -------------------------------------- 1.2/101.7 MB 425.0 kB/s eta 0:03:57
     -------------------------------------- 1.2/101.7 MB 422.8 kB/s eta 0:03:58
     -------------------------------------- 1.3/101.7 MB 420.9 kB/s eta 0:03:59
     -------------------------------------- 1.3/101.7 MB 436.9 kB/s eta 0:03:50
     -------------------------------------- 1.3/101.7 MB 436.9 kB/s eta 0:03:50
     -------------------------------------- 1.3/101.7 MB 436.9 kB/s eta 0:03:50
     -------------------------------------- 1.3/101.7 MB 418.6 kB/s eta 0:04:00
      ------------------------------------- 1.4/101.7 MB 432.6 kB/s eta 0:03:52
      ------------------------------------- 1.4/101.7 MB 440.1 kB/s eta 0:03:48
      ------------------------------------- 1.5/101.7 MB 443.2 kB/s eta 0:03:47
      ------------------------------------- 1.5/101.7 MB 443.2 kB/s eta 0:03:47
      ------------------------------------- 1.5/101.7 MB 444.0 kB/s eta 0:03:46
      ------------------------------------- 1.5/101.7 MB 443.9 kB/s eta 0:03:46
      ------------------------------------- 1.5/101.7 MB 443.9 kB/s eta 0:03:46
      ------------------------------------- 1.6/101.7 MB 440.8 kB/s eta 0:03:48
      ------------------------------------- 1.6/101.7 MB 437.9 kB/s eta 0:03:49
      ------------------------------------- 1.6/101.7 MB 439.8 kB/s eta 0:03:48
      ------------------------------------- 1.6/101.7 MB 439.7 kB/s eta 0:03:48
      ------------------------------------- 1.6/101.7 MB 438.8 kB/s eta 0:03:48
      ------------------------------------- 1.7/101.7 MB 437.9 kB/s eta 0:03:49
      ------------------------------------- 1.7/101.7 MB 445.0 kB/s eta 0:03:45
      ------------------------------------- 1.7/101.7 MB 445.0 kB/s eta 0:03:45
      ------------------------------------- 1.7/101.7 MB 443.1 kB/s eta 0:03:46
      ------------------------------------- 1.8/101.7 MB 461.9 kB/s eta 0:03:37
      ------------------------------------- 1.9/101.7 MB 464.2 kB/s eta 0:03:36
      ------------------------------------- 1.9/101.7 MB 464.2 kB/s eta 0:03:36
      ------------------------------------- 1.9/101.7 MB 464.5 kB/s eta 0:03:35
      ------------------------------------- 1.9/101.7 MB 465.7 kB/s eta 0:03:35
      ------------------------------------- 1.9/101.7 MB 465.7 kB/s eta 0:03:35
      ------------------------------------- 1.9/101.7 MB 465.7 kB/s eta 0:03:35
      ------------------------------------- 2.0/101.7 MB 458.3 kB/s eta 0:03:38
      ------------------------------------- 2.0/101.7 MB 458.1 kB/s eta 0:03:38
      ------------------------------------- 2.0/101.7 MB 459.5 kB/s eta 0:03:37
      ------------------------------------- 2.1/101.7 MB 461.6 kB/s eta 0:03:36
      ------------------------------------- 2.1/101.7 MB 466.5 kB/s eta 0:03:34
      ------------------------------------- 2.2/101.7 MB 471.4 kB/s eta 0:03:32
      ------------------------------------- 2.2/101.7 MB 471.4 kB/s eta 0:03:32
      ------------------------------------- 2.2/101.7 MB 473.2 kB/s eta 0:03:31
      ------------------------------------- 2.2/101.7 MB 469.0 kB/s eta 0:03:33
      ------------------------------------- 2.2/101.7 MB 467.8 kB/s eta 0:03:33
      ------------------------------------- 2.3/101.7 MB 469.1 kB/s eta 0:03:32
      ------------------------------------- 2.3/101.7 MB 469.4 kB/s eta 0:03:32
      ------------------------------------- 2.3/101.7 MB 470.5 kB/s eta 0:03:32
      ------------------------------------- 2.3/101.7 MB 470.8 kB/s eta 0:03:32
      ------------------------------------- 2.4/101.7 MB 473.4 kB/s eta 0:03:30
      ------------------------------------- 2.4/101.7 MB 473.4 kB/s eta 0:03:30
      ------------------------------------- 2.5/101.7 MB 490.0 kB/s eta 0:03:23
      ------------------------------------- 2.6/101.7 MB 501.5 kB/s eta 0:03:18
      ------------------------------------- 2.6/101.7 MB 506.9 kB/s eta 0:03:16
      ------------------------------------- 2.7/101.7 MB 509.7 kB/s eta 0:03:15
     - ------------------------------------ 2.7/101.7 MB 519.3 kB/s eta 0:03:11
     - ------------------------------------ 2.8/101.7 MB 526.3 kB/s eta 0:03:08
     - ------------------------------------ 2.8/101.7 MB 527.0 kB/s eta 0:03:08
     - ------------------------------------ 2.8/101.7 MB 527.0 kB/s eta 0:03:08
     - ------------------------------------ 3.0/101.7 MB 539.3 kB/s eta 0:03:04
     - ------------------------------------ 3.1/101.7 MB 555.2 kB/s eta 0:02:58
     - ------------------------------------ 3.1/101.7 MB 561.5 kB/s eta 0:02:56
     - ------------------------------------ 3.2/101.7 MB 565.9 kB/s eta 0:02:55
     - ------------------------------------ 3.3/101.7 MB 573.9 kB/s eta 0:02:52
     - ------------------------------------ 3.3/101.7 MB 576.2 kB/s eta 0:02:51
     - ------------------------------------ 3.3/101.7 MB 578.4 kB/s eta 0:02:51
     - ------------------------------------ 3.3/101.7 MB 578.4 kB/s eta 0:02:51
     - ------------------------------------ 3.5/101.7 MB 590.6 kB/s eta 0:02:47
     - ------------------------------------ 3.5/101.7 MB 594.6 kB/s eta 0:02:46
     - ------------------------------------ 3.6/101.7 MB 601.9 kB/s eta 0:02:43
     - ------------------------------------ 3.6/101.7 MB 604.2 kB/s eta 0:02:43
     - ------------------------------------ 3.7/101.7 MB 612.9 kB/s eta 0:02:40
     - ------------------------------------ 3.8/101.7 MB 621.7 kB/s eta 0:02:38
     - ------------------------------------ 3.8/101.7 MB 621.9 kB/s eta 0:02:38
     - ------------------------------------ 3.8/101.7 MB 621.9 kB/s eta 0:02:38
     - ------------------------------------ 4.0/101.7 MB 640.6 kB/s eta 0:02:33
     - ------------------------------------ 4.1/101.7 MB 647.2 kB/s eta 0:02:31
     - ------------------------------------ 4.1/101.7 MB 652.1 kB/s eta 0:02:30
     - ------------------------------------ 4.2/101.7 MB 661.8 kB/s eta 0:02:28
     - ------------------------------------ 4.3/101.7 MB 669.8 kB/s eta 0:02:26
     - ------------------------------------ 4.4/101.7 MB 679.2 kB/s eta 0:02:24
     - ------------------------------------ 4.4/101.7 MB 679.2 kB/s eta 0:02:24
     - ------------------------------------ 4.4/101.7 MB 679.2 kB/s eta 0:02:24
     - ------------------------------------ 4.6/101.7 MB 698.8 kB/s eta 0:02:19
     - ------------------------------------ 4.7/101.7 MB 698.5 kB/s eta 0:02:19
     - ------------------------------------ 4.7/101.7 MB 698.5 kB/s eta 0:02:19
     - ------------------------------------ 4.7/101.7 MB 693.3 kB/s eta 0:02:20
     - ------------------------------------ 4.7/101.7 MB 696.0 kB/s eta 0:02:20
     - ------------------------------------ 4.8/101.7 MB 695.8 kB/s eta 0:02:20
     - ------------------------------------ 4.8/101.7 MB 695.8 kB/s eta 0:02:20
     - ------------------------------------ 4.8/101.7 MB 695.8 kB/s eta 0:02:20
     - ------------------------------------ 4.9/101.7 MB 697.8 kB/s eta 0:02:19
     - ------------------------------------ 4.9/101.7 MB 700.5 kB/s eta 0:02:19
     - ------------------------------------ 5.0/101.7 MB 706.0 kB/s eta 0:02:17
     - ------------------------------------ 5.1/101.7 MB 710.0 kB/s eta 0:02:17
     - ------------------------------------ 5.2/101.7 MB 718.3 kB/s eta 0:02:15
     - ------------------------------------ 5.2/101.7 MB 723.5 kB/s eta 0:02:14
     - ------------------------------------ 5.3/101.7 MB 724.6 kB/s eta 0:02:14
     - ------------------------------------ 5.3/101.7 MB 724.6 kB/s eta 0:02:14
     -- ----------------------------------- 5.4/101.7 MB 731.9 kB/s eta 0:02:12
     -- ----------------------------------- 5.5/101.7 MB 746.9 kB/s eta 0:02:09
     -- ----------------------------------- 5.6/101.7 MB 752.2 kB/s eta 0:02:08
     -- ----------------------------------- 5.7/101.7 MB 763.5 kB/s eta 0:02:06
     -- ----------------------------------- 5.8/101.7 MB 769.6 kB/s eta 0:02:05
     -- ----------------------------------- 5.9/101.7 MB 777.3 kB/s eta 0:02:04
     -- ----------------------------------- 5.9/101.7 MB 776.8 kB/s eta 0:02:04
     -- ----------------------------------- 5.9/101.7 MB 776.8 kB/s eta 0:02:04
     -- ----------------------------------- 6.0/101.7 MB 776.2 kB/s eta 0:02:04
     -- ----------------------------------- 6.1/101.7 MB 780.7 kB/s eta 0:02:03
     -- ----------------------------------- 6.1/101.7 MB 779.9 kB/s eta 0:02:03
     -- ----------------------------------- 6.2/101.7 MB 783.4 kB/s eta 0:02:02
     -- ----------------------------------- 6.2/101.7 MB 785.2 kB/s eta 0:02:02
     -- ----------------------------------- 6.2/101.7 MB 785.7 kB/s eta 0:02:02
     -- ----------------------------------- 6.3/101.7 MB 787.5 kB/s eta 0:02:02
     -- ----------------------------------- 6.3/101.7 MB 787.5 kB/s eta 0:02:02
     -- ----------------------------------- 6.3/101.7 MB 787.5 kB/s eta 0:02:02
     -- ----------------------------------- 6.4/101.7 MB 789.2 kB/s eta 0:02:01
     -- ----------------------------------- 6.5/101.7 MB 791.7 kB/s eta 0:02:01
     -- ----------------------------------- 6.5/101.7 MB 793.7 kB/s eta 0:02:00
     -- ----------------------------------- 6.6/101.7 MB 794.2 kB/s eta 0:02:00
     -- ----------------------------------- 6.6/101.7 MB 798.3 kB/s eta 0:02:00
     -- ----------------------------------- 6.7/101.7 MB 799.9 kB/s eta 0:01:59
     -- ----------------------------------- 6.7/101.7 MB 799.9 kB/s eta 0:01:59
     -- ----------------------------------- 6.7/101.7 MB 799.9 kB/s eta 0:01:59
     -- ----------------------------------- 6.8/101.7 MB 799.7 kB/s eta 0:01:59
     -- ----------------------------------- 6.9/101.7 MB 800.1 kB/s eta 0:01:59
     -- ----------------------------------- 6.9/101.7 MB 800.5 kB/s eta 0:01:59
     -- ----------------------------------- 6.9/101.7 MB 798.5 kB/s eta 0:01:59
     -- ----------------------------------- 6.9/101.7 MB 798.0 kB/s eta 0:01:59
     -- ----------------------------------- 7.0/101.7 MB 796.4 kB/s eta 0:01:59
     -- ----------------------------------- 7.0/101.7 MB 796.4 kB/s eta 0:01:59
     -- ----------------------------------- 7.0/101.7 MB 796.4 kB/s eta 0:01:59
     -- ----------------------------------- 7.0/101.7 MB 790.2 kB/s eta 0:02:00
     -- ----------------------------------- 7.1/101.7 MB 789.5 kB/s eta 0:02:00
     -- ----------------------------------- 7.1/101.7 MB 789.9 kB/s eta 0:02:00
     -- ----------------------------------- 7.1/101.7 MB 789.6 kB/s eta 0:02:00
     -- ----------------------------------- 7.1/101.7 MB 788.9 kB/s eta 0:02:00
     -- ----------------------------------- 7.2/101.7 MB 788.5 kB/s eta 0:02:00
     -- ----------------------------------- 7.2/101.7 MB 786.5 kB/s eta 0:02:01
     -- ----------------------------------- 7.2/101.7 MB 786.5 kB/s eta 0:02:01
     -- ----------------------------------- 7.3/101.7 MB 784.9 kB/s eta 0:02:01
     -- ----------------------------------- 7.3/101.7 MB 785.6 kB/s eta 0:02:01
     -- ----------------------------------- 7.3/101.7 MB 784.1 kB/s eta 0:02:01
     -- ----------------------------------- 7.4/101.7 MB 781.9 kB/s eta 0:02:01
     -- ----------------------------------- 7.4/101.7 MB 779.9 kB/s eta 0:02:01
     -- ----------------------------------- 7.4/101.7 MB 779.8 kB/s eta 0:02:01
     -- ----------------------------------- 7.4/101.7 MB 779.3 kB/s eta 0:02:01
     -- ----------------------------------- 7.4/101.7 MB 779.3 kB/s eta 0:02:01
     -- ----------------------------------- 7.5/101.7 MB 777.7 kB/s eta 0:02:02
     -- ----------------------------------- 7.5/101.7 MB 778.4 kB/s eta 0:02:01
     -- ----------------------------------- 7.6/101.7 MB 777.8 kB/s eta 0:02:02
     -- ----------------------------------- 7.6/101.7 MB 779.3 kB/s eta 0:02:01
     -- ----------------------------------- 7.6/101.7 MB 778.7 kB/s eta 0:02:01
     -- ----------------------------------- 7.7/101.7 MB 779.6 kB/s eta 0:02:01
     -- ----------------------------------- 7.7/101.7 MB 780.8 kB/s eta 0:02:01
     -- ----------------------------------- 7.7/101.7 MB 780.8 kB/s eta 0:02:01
     -- ----------------------------------- 7.8/101.7 MB 776.4 kB/s eta 0:02:01
     -- ----------------------------------- 7.8/101.7 MB 778.2 kB/s eta 0:02:01
     -- ----------------------------------- 7.9/101.7 MB 777.2 kB/s eta 0:02:01
     -- ----------------------------------- 7.9/101.7 MB 778.0 kB/s eta 0:02:01
     -- ----------------------------------- 7.9/101.7 MB 775.0 kB/s eta 0:02:02
     -- ----------------------------------- 7.9/101.7 MB 773.5 kB/s eta 0:02:02
     -- ----------------------------------- 8.0/101.7 MB 772.9 kB/s eta 0:02:02
     -- ----------------------------------- 8.0/101.7 MB 772.9 kB/s eta 0:02:02
     -- ----------------------------------- 8.0/101.7 MB 771.8 kB/s eta 0:02:02
     --- ---------------------------------- 8.1/101.7 MB 772.3 kB/s eta 0:02:02
     --- ---------------------------------- 8.1/101.7 MB 772.8 kB/s eta 0:02:02
     --- ---------------------------------- 8.1/101.7 MB 772.3 kB/s eta 0:02:02
     --- ---------------------------------- 8.2/101.7 MB 772.5 kB/s eta 0:02:02
     --- ---------------------------------- 8.2/101.7 MB 773.3 kB/s eta 0:02:01
     --- ---------------------------------- 8.2/101.7 MB 772.8 kB/s eta 0:02:01
     --- ---------------------------------- 8.2/101.7 MB 772.8 kB/s eta 0:02:01
     --- ---------------------------------- 8.3/101.7 MB 767.8 kB/s eta 0:02:02
     --- ---------------------------------- 8.3/101.7 MB 768.4 kB/s eta 0:02:02
     --- ---------------------------------- 8.3/101.7 MB 767.8 kB/s eta 0:02:02
     --- ---------------------------------- 8.3/101.7 MB 767.8 kB/s eta 0:02:02
     --- ---------------------------------- 8.4/101.7 MB 765.0 kB/s eta 0:02:02
     --- ---------------------------------- 8.4/101.7 MB 763.5 kB/s eta 0:02:03
     --- ---------------------------------- 8.4/101.7 MB 763.1 kB/s eta 0:02:03
     --- ---------------------------------- 8.4/101.7 MB 763.1 kB/s eta 0:02:03
     --- ---------------------------------- 8.5/101.7 MB 762.9 kB/s eta 0:02:03
     --- ---------------------------------- 8.6/101.7 MB 764.3 kB/s eta 0:02:02
     --- ---------------------------------- 8.6/101.7 MB 764.0 kB/s eta 0:02:02
     --- ---------------------------------- 8.6/101.7 MB 763.4 kB/s eta 0:02:02
     --- ---------------------------------- 8.7/101.7 MB 764.7 kB/s eta 0:02:02
     --- ---------------------------------- 8.7/101.7 MB 764.5 kB/s eta 0:02:02
     --- ---------------------------------- 8.7/101.7 MB 764.7 kB/s eta 0:02:02
     --- ---------------------------------- 8.7/101.7 MB 764.7 kB/s eta 0:02:02
     --- ---------------------------------- 8.8/101.7 MB 763.9 kB/s eta 0:02:02
     --- ---------------------------------- 8.8/101.7 MB 763.4 kB/s eta 0:02:02
     --- ---------------------------------- 8.9/101.7 MB 762.1 kB/s eta 0:02:02
     --- ---------------------------------- 8.9/101.7 MB 763.4 kB/s eta 0:02:02
     --- ---------------------------------- 8.9/101.7 MB 763.0 kB/s eta 0:02:02
     --- ---------------------------------- 9.0/101.7 MB 763.3 kB/s eta 0:02:02

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

     ----- ------------------------------- 13.8/101.7 MB 654.1 kB/s eta 0:02:15
     ----- ------------------------------- 13.8/101.7 MB 653.4 kB/s eta 0:02:15
     ----- ------------------------------- 13.9/101.7 MB 652.7 kB/s eta 0:02:15
     ----- ------------------------------- 13.9/101.7 MB 652.1 kB/s eta 0:02:15
     ----- ------------------------------- 13.9/101.7 MB 652.1 kB/s eta 0:02:15
     ----- ------------------------------- 14.0/101.7 MB 649.5 kB/s eta 0:02:16
     ----- ------------------------------- 14.0/101.7 MB 648.9 kB/s eta 0:02:16
     ----- ------------------------------- 14.0/101.7 MB 647.6 kB/s eta 0:02:16
     ----- ------------------------------- 14.1/101.7 MB 649.5 kB/s eta 0:02:15
     ----- ------------------------------- 14.1/101.7 MB 648.2 kB/s eta 0:02:16
     ----- ------------------------------- 14.2/101.7 MB 646.3 kB/s eta 0:02:16
     ----- ------------------------------- 14.2/101.7 MB 646.3 kB/s eta 0:02:16
     ----- ------------------------------- 14.2/101.7 MB 646.3 kB/s eta 0:02:16
     ----- ------------------------------- 14.3/101.7 MB 643.1 kB/s eta 0:02:16
     ----- ------------------------------- 14.3/101.7 MB 642.5 kB/s eta 0:02:17
     ----- ------------------------------- 14.3/101.7 MB 640.0 kB/s eta 0:02:17
     ----- ------------------------------- 14.4/101.7 MB 640.0 kB/s eta 0:02:17
     ----- ------------------------------- 14.4/101.7 MB 638.7 kB/s eta 0:02:17
     ----- ------------------------------- 14.4/101.7 MB 636.9 kB/s eta 0:02:17
     ----- ------------------------------- 14.4/101.7 MB 636.9 kB/s eta 0:02:17
     ----- ------------------------------- 14.4/101.7 MB 636.9 kB/s eta 0:02:17
     ----- ------------------------------- 14.5/101.7 MB 633.8 kB/s eta 0:02:18
     ----- ------------------------------- 14.5/101.7 MB 632.6 kB/s eta 0:02:18
     ----- ------------------------------- 14.6/101.7 MB 630.1 kB/s eta 0:02:19
     ----- ------------------------------- 14.6/101.7 MB 629.5 kB/s eta 0:02:19
     ----- ------------------------------- 14.6/101.7 MB 627.7 kB/s eta 0:02:19
     ----- ------------------------------- 14.6/101.7 MB 627.1 kB/s eta 0:02:19
     ----- ------------------------------- 14.6/101.7 MB 627.1 kB/s eta 0:02:19
     ----- ------------------------------- 14.6/101.7 MB 627.1 kB/s eta 0:02:19
     ----- ------------------------------- 14.7/101.7 MB 625.3 kB/s eta 0:02:20
     ----- ------------------------------- 14.7/101.7 MB 624.1 kB/s eta 0:02:20
     ----- ------------------------------- 14.7/101.7 MB 621.7 kB/s eta 0:02:20
     ----- ------------------------------- 14.7/101.7 MB 620.0 kB/s eta 0:02:21
     ----- ------------------------------- 14.7/101.7 MB 620.0 kB/s eta 0:02:21
     ----- ------------------------------- 14.8/101.7 MB 615.9 kB/s eta 0:02:22
     ----- ------------------------------- 14.8/101.7 MB 615.9 kB/s eta 0:02:22
     ----- ------------------------------- 14.8/101.7 MB 615.9 kB/s eta 0:02:22
     ----- ------------------------------- 14.8/101.7 MB 611.3 kB/s eta 0:02:23
     ----- ------------------------------- 14.8/101.7 MB 609.0 kB/s eta 0:02:23
     ----- ------------------------------- 14.8/101.7 MB 607.9 kB/s eta 0:02:23
     ----- ------------------------------- 14.9/101.7 MB 607.4 kB/s eta 0:02:23
     ----- ------------------------------- 14.9/101.7 MB 607.3 kB/s eta 0:02:23
     ----- ------------------------------- 14.9/101.7 MB 608.5 kB/s eta 0:02:23
     ----- ------------------------------- 14.9/101.7 MB 608.5 kB/s eta 0:02:23
     ----- ------------------------------- 14.9/101.7 MB 608.5 kB/s eta 0:02:23
     ----- ------------------------------- 15.0/101.7 MB 606.2 kB/s eta 0:02:23
     ----- ------------------------------- 15.0/101.7 MB 608.5 kB/s eta 0:02:23
     ----- ------------------------------- 15.1/101.7 MB 607.3 kB/s eta 0:02:23
     ----- ------------------------------- 15.1/101.7 MB 606.8 kB/s eta 0:02:23
     ----- ------------------------------- 15.1/101.7 MB 605.1 kB/s eta 0:02:24
     ----- ------------------------------- 15.1/101.7 MB 604.0 kB/s eta 0:02:24
     ----- ------------------------------- 15.1/101.7 MB 604.0 kB/s eta 0:02:24
     ----- ------------------------------- 15.2/101.7 MB 601.2 kB/s eta 0:02:24
     ----- ------------------------------- 15.2/101.7 MB 600.7 kB/s eta 0:02:24
     ----- ------------------------------- 15.3/101.7 MB 600.1 kB/s eta 0:02:24
     ----- ------------------------------- 15.3/101.7 MB 599.0 kB/s eta 0:02:25
     ----- ------------------------------- 15.3/101.7 MB 598.4 kB/s eta 0:02:25
     ----- ------------------------------- 15.4/101.7 MB 597.4 kB/s eta 0:02:25
     ----- ------------------------------- 15.4/101.7 MB 596.8 kB/s eta 0:02:25
     ----- ------------------------------- 15.4/101.7 MB 596.8 kB/s eta 0:02:25
     ----- ------------------------------- 15.4/101.7 MB 593.0 kB/s eta 0:02:26
     ----- ------------------------------- 15.5/101.7 MB 597.4 kB/s eta 0:02:25
     ----- ------------------------------- 15.6/101.7 MB 594.6 kB/s eta 0:02:25
     ----- ------------------------------- 15.6/101.7 MB 593.5 kB/s eta 0:02:26
     ----- ------------------------------- 15.6/101.7 MB 592.5 kB/s eta 0:02:26
     ----- ------------------------------- 15.7/101.7 MB 590.4 kB/s eta 0:02:26
     ----- ------------------------------- 15.7/101.7 MB 590.4 kB/s eta 0:02:26
     ----- ------------------------------- 15.7/101.7 MB 590.4 kB/s eta 0:02:26
     ----- ------------------------------- 15.7/101.7 MB 585.6 kB/s eta 0:02:27
     ----- ------------------------------- 15.8/101.7 MB 585.1 kB/s eta 0:02:27
     ----- ------------------------------- 15.8/101.7 MB 584.0 kB/s eta 0:02:28
     ----- ------------------------------- 15.8/101.7 MB 584.1 kB/s eta 0:02:27
     ----- ------------------------------- 15.9/101.7 MB 582.5 kB/s eta 0:02:28
     ----- ------------------------------- 15.9/101.7 MB 581.4 kB/s eta 0:02:28
     ----- ------------------------------- 15.9/101.7 MB 580.9 kB/s eta 0:02:28
     ----- ------------------------------- 15.9/101.7 MB 580.9 kB/s eta 0:02:28
     ----- ------------------------------- 16.0/101.7 MB 578.4 kB/s eta 0:02:29
     ----- ------------------------------- 16.1/101.7 MB 577.4 kB/s eta 0:02:29
     ----- ------------------------------- 16.1/101.7 MB 575.8 kB/s eta 0:02:29
     ----- ------------------------------- 16.1/101.7 MB 575.8 kB/s eta 0:02:29
     ----- ------------------------------- 16.1/101.7 MB 578.9 kB/s eta 0:02:28
     ----- ------------------------------- 16.2/101.7 MB 576.8 kB/s eta 0:02:29
     ----- ------------------------------- 16.2/101.7 MB 575.8 kB/s eta 0:02:29
     ----- ------------------------------- 16.2/101.7 MB 575.8 kB/s eta 0:02:29
     ----- ------------------------------- 16.3/101.7 MB 572.8 kB/s eta 0:02:30
     ----- ------------------------------- 16.3/101.7 MB 572.3 kB/s eta 0:02:30
     ----- ------------------------------- 16.3/101.7 MB 572.3 kB/s eta 0:02:30
     ----- ------------------------------- 16.4/101.7 MB 571.3 kB/s eta 0:02:30
     ----- ------------------------------- 16.4/101.7 MB 570.3 kB/s eta 0:02:30
     ----- ------------------------------- 16.4/101.7 MB 570.8 kB/s eta 0:02:30
     ----- ------------------------------- 16.4/101.7 MB 570.8 kB/s eta 0:02:30
     ----- ------------------------------- 16.4/101.7 MB 570.8 kB/s eta 0:02:30
     ------ ------------------------------ 16.6/101.7 MB 571.3 kB/s eta 0:02:29
     ------ ------------------------------ 16.6/101.7 MB 570.8 kB/s eta 0:02:30
     ------ ------------------------------ 16.6/101.7 MB 569.3 kB/s eta 0:02:30
     ------ ------------------------------ 16.7/101.7 MB 568.8 kB/s eta 0:02:30
     ------ ------------------------------ 16.7/101.7 MB 568.8 kB/s eta 0:02:30
     ------ ------------------------------ 16.7/101.7 MB 567.3 kB/s eta 0:02:30
     ------ ------------------------------ 16.7/101.7 MB 567.3 kB/s eta 0:02:30
     ------ ------------------------------ 16.7/101.7 MB 567.3 kB/s eta 0:02:30
     ------ ------------------------------ 16.9/101.7 MB 566.8 kB/s eta 0:02:30
     ------ ------------------------------ 16.9/101.7 MB 566.8 kB/s eta 0:02:30
     ------ ------------------------------ 16.9/101.7 MB 565.4 kB/s eta 0:02:30
     ------ ------------------------------ 16.9/101.7 MB 567.3 kB/s eta 0:02:30
     ------ ------------------------------ 17.0/101.7 MB 565.9 kB/s eta 0:02:30
     ------ ------------------------------ 17.0/101.7 MB 564.9 kB/s eta 0:02:30
     ------ ------------------------------ 17.0/101.7 MB 564.9 kB/s eta 0:02:30
     ------ ------------------------------ 17.0/101.7 MB 564.9 kB/s eta 0:02:30
     ------ ------------------------------ 17.1/101.7 MB 562.0 kB/s eta 0:02:31
     ------ ------------------------------ 17.1/101.7 MB 561.5 kB/s eta 0:02:31
     ------ ------------------------------ 17.1/101.7 MB 560.5 kB/s eta 0:02:31
     ------ ------------------------------ 17.1/101.7 MB 559.6 kB/s eta 0:02:32
     ------ ------------------------------ 17.2/101.7 MB 559.6 kB/s eta 0:02:32
     ------ ------------------------------ 17.2/101.7 MB 559.6 kB/s eta 0:02:32
     ------ ------------------------------ 17.2/101.7 MB 559.6 kB/s eta 0:02:32
     ------ ------------------------------ 17.2/101.7 MB 559.6 kB/s eta 0:02:32
     ------ ------------------------------ 17.3/101.7 MB 560.5 kB/s eta 0:02:31
     ------ ------------------------------ 17.3/101.7 MB 560.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.3/101.7 MB 559.6 kB/s eta 0:02:31
     ------ ------------------------------ 17.3/101.7 MB 559.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.4/101.7 MB 559.6 kB/s eta 0:02:31
     ------ ------------------------------ 17.4/101.7 MB 561.0 kB/s eta 0:02:31
     ------ ------------------------------ 17.4/101.7 MB 561.0 kB/s eta 0:02:31
     ------ ------------------------------ 17.5/101.7 MB 560.5 kB/s eta 0:02:31
     ------ ------------------------------ 17.5/101.7 MB 560.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.5/101.7 MB 559.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.5/101.7 MB 559.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.6/101.7 MB 559.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.6/101.7 MB 560.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.6/101.7 MB 560.5 kB/s eta 0:02:30
     ------ ------------------------------ 17.6/101.7 MB 560.5 kB/s eta 0:02:30
     ------ ------------------------------ 17.6/101.7 MB 560.5 kB/s eta 0:02:30
     ------ ------------------------------ 17.7/101.7 MB 560.1 kB/s eta 0:02:30
     ------ ------------------------------ 17.8/101.7 MB 559.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.8/101.7 MB 559.1 kB/s eta 0:02:31
     ------ ------------------------------ 17.8/101.7 MB 558.6 kB/s eta 0:02:31
     ------ ------------------------------ 17.8/101.7 MB 557.7 kB/s eta 0:02:31
     ------ ------------------------------ 17.8/101.7 MB 557.2 kB/s eta 0:02:31
     ------ ------------------------------ 17.8/101.7 MB 557.2 kB/s eta 0:02:31
     ------ ------------------------------ 17.9/101.7 MB 554.8 kB/s eta 0:02:32
     ------ ------------------------------ 17.9/101.7 MB 555.8 kB/s eta 0:02:31
     ------ ------------------------------ 17.9/101.7 MB 553.9 kB/s eta 0:02:32
     ------ ------------------------------ 17.9/101.7 MB 552.5 kB/s eta 0:02:32
     ------ ------------------------------ 18.0/101.7 MB 552.0 kB/s eta 0:02:32
     ------ ------------------------------ 18.0/101.7 MB 553.4 kB/s eta 0:02:32
     ------ ------------------------------ 18.0/101.7 MB 552.5 kB/s eta 0:02:32
     ------ ------------------------------ 18.0/101.7 MB 552.5 kB/s eta 0:02:32
     ------ ------------------------------ 18.0/101.7 MB 549.2 kB/s eta 0:02:33
     ------ ------------------------------ 18.0/101.7 MB 549.7 kB/s eta 0:02:33
     ------ ------------------------------ 18.0/101.7 MB 548.3 kB/s eta 0:02:33
     ------ ------------------------------ 18.1/101.7 MB 547.4 kB/s eta 0:02:33
     ------ ------------------------------ 18.1/101.7 MB 546.9 kB/s eta 0:02:33
     ------ ------------------------------ 18.1/101.7 MB 546.1 kB/s eta 0:02:34
     ------ ------------------------------ 18.1/101.7 MB 546.1 kB/s eta 0:02:34
     ------ ------------------------------ 18.1/101.7 MB 546.1 kB/s eta 0:02:34
     ------ ------------------------------ 18.1/101.7 MB 545.1 kB/s eta 0:02:34
     ------ ------------------------------ 18.2/101.7 MB 545.1 kB/s eta 0:02:34
     ------ ------------------------------ 18.2/101.7 MB 546.5 kB/s eta 0:02:33
     ------ ------------------------------ 18.2/101.7 MB 545.2 kB/s eta 0:02:34
     ------ ------------------------------ 18.2/101.7 MB 543.8 kB/s eta 0:02:34
     ------ ------------------------------ 18.2/101.7 MB 542.4 kB/s eta 0:02:34
     ------ ------------------------------ 18.3/101.7 MB 541.5 kB/s eta 0:02:35
     ------ ------------------------------ 18.3/101.7 MB 541.5 kB/s eta 0:02:35
     ------ ------------------------------ 18.3/101.7 MB 539.3 kB/s eta 0:02:35
     ------ ------------------------------ 18.3/101.7 MB 538.9 kB/s eta 0:02:35
     ------ ------------------------------ 18.3/101.7 MB 538.0 kB/s eta 0:02:35
     ------ ------------------------------ 18.3/101.7 MB 536.6 kB/s eta 0:02:36
     ------ ------------------------------ 18.4/101.7 MB 536.2 kB/s eta 0:02:36
     ------ ------------------------------ 18.4/101.7 MB 536.2 kB/s eta 0:02:36
     ------ ------------------------------ 18.4/101.7 MB 534.9 kB/s eta 0:02:36
     ------ ------------------------------ 18.4/101.7 MB 534.9 kB/s eta 0:02:36
     ------ ------------------------------ 18.4/101.7 MB 533.1 kB/s eta 0:02:37
     ------ ------------------------------ 18.4/101.7 MB 532.3 kB/s eta 0:02:37
     ------ ------------------------------ 18.4/101.7 MB 532.3 kB/s eta 0:02:37
     ------ ------------------------------ 18.5/101.7 MB 533.2 kB/s eta 0:02:37
     ------ ------------------------------ 18.5/101.7 MB 532.3 kB/s eta 0:02:37
     ------ ------------------------------ 18.5/101.7 MB 531.4 kB/s eta 0:02:37
     ------ ------------------------------ 18.5/101.7 MB 531.4 kB/s eta 0:02:37
     ------ ------------------------------ 18.5/101.7 MB 531.4 kB/s eta 0:02:37
     ------ ------------------------------ 18.6/101.7 MB 531.4 kB/s eta 0:02:37
     ------ ------------------------------ 18.6/101.7 MB 531.0 kB/s eta 0:02:37
     ------ ------------------------------ 18.6/101.7 MB 530.6 kB/s eta 0:02:37
     ------ ------------------------------ 18.6/101.7 MB 530.6 kB/s eta 0:02:37
     ------ ------------------------------ 18.7/101.7 MB 532.3 kB/s eta 0:02:36
     ------ ------------------------------ 18.7/101.7 MB 531.0 kB/s eta 0:02:37
     ------ ------------------------------ 18.7/101.7 MB 530.5 kB/s eta 0:02:37
     ------ ------------------------------ 18.7/101.7 MB 530.5 kB/s eta 0:02:37
     ------ ------------------------------ 18.8/101.7 MB 528.4 kB/s eta 0:02:37
     ------ ------------------------------ 18.8/101.7 MB 529.3 kB/s eta 0:02:37
     ------ ------------------------------ 18.8/101.7 MB 527.6 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 527.1 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 526.3 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 526.3 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 526.3 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 526.3 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 525.0 kB/s eta 0:02:38
     ------ ------------------------------ 18.9/101.7 MB 523.8 kB/s eta 0:02:38
     ------ ------------------------------ 19.0/101.7 MB 524.2 kB/s eta 0:02:38
     ------ ------------------------------ 19.0/101.7 MB 523.3 kB/s eta 0:02:38
     ------ ------------------------------ 19.0/101.7 MB 522.1 kB/s eta 0:02:39
     ------ ------------------------------ 19.0/101.7 MB 520.8 kB/s eta 0:02:39
     ------ ------------------------------ 19.0/101.7 MB 520.8 kB/s eta 0:02:39
     ------ ------------------------------ 19.0/101.7 MB 520.8 kB/s eta 0:02:39
     ------ ------------------------------ 19.1/101.7 MB 520.4 kB/s eta 0:02:39
     ------ ------------------------------ 19.1/101.7 MB 519.6 kB/s eta 0:02:39
     ------ ------------------------------ 19.2/101.7 MB 519.6 kB/s eta 0:02:39
     ------ ------------------------------ 19.2/101.7 MB 518.8 kB/s eta 0:02:40
     ------ ------------------------------ 19.2/101.7 MB 518.4 kB/s eta 0:02:40
     ------ ------------------------------ 19.2/101.7 MB 518.4 kB/s eta 0:02:40
     ------ ------------------------------ 19.2/101.7 MB 517.5 kB/s eta 0:02:40
     ------ ------------------------------ 19.2/101.7 MB 517.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.3/101.7 MB 518.4 kB/s eta 0:02:39
     ------- ----------------------------- 19.3/101.7 MB 517.6 kB/s eta 0:02:40
     ------- ----------------------------- 19.3/101.7 MB 516.3 kB/s eta 0:02:40
     ------- ----------------------------- 19.3/101.7 MB 515.9 kB/s eta 0:02:40
     ------- ----------------------------- 19.4/101.7 MB 515.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.4/101.7 MB 515.1 kB/s eta 0:02:40
     ------- ----------------------------- 19.4/101.7 MB 515.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.4/101.7 MB 515.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.4/101.7 MB 515.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.5/101.7 MB 517.5 kB/s eta 0:02:39
     ------- ----------------------------- 19.5/101.7 MB 516.7 kB/s eta 0:02:40
     ------- ----------------------------- 19.5/101.7 MB 515.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.5/101.7 MB 514.7 kB/s eta 0:02:40
     ------- ----------------------------- 19.6/101.7 MB 513.5 kB/s eta 0:02:40
     ------- ----------------------------- 19.6/101.7 MB 513.1 kB/s eta 0:02:40
     ------- ----------------------------- 19.6/101.7 MB 512.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.6/101.7 MB 512.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.6/101.7 MB 512.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.7/101.7 MB 511.9 kB/s eta 0:02:41
     ------- ----------------------------- 19.7/101.7 MB 511.5 kB/s eta 0:02:41
     ------- ----------------------------- 19.7/101.7 MB 510.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.7/101.7 MB 510.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.7/101.7 MB 510.3 kB/s eta 0:02:41
     ------- ----------------------------- 19.7/101.7 MB 512.7 kB/s eta 0:02:40
     ------- ----------------------------- 19.8/101.7 MB 510.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.8/101.7 MB 510.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.8/101.7 MB 510.7 kB/s eta 0:02:41
     ------- ----------------------------- 19.8/101.7 MB 509.1 kB/s eta 0:02:41
     ------- ----------------------------- 19.8/101.7 MB 509.5 kB/s eta 0:02:41
     ------- ----------------------------- 19.8/101.7 MB 509.9 kB/s eta 0:02:41
     ------- ----------------------------- 19.9/101.7 MB 509.9 kB/s eta 0:02:41
     ------- ----------------------------- 19.9/101.7 MB 511.9 kB/s eta 0:02:40
     ------- ----------------------------- 19.9/101.7 MB 511.9 kB/s eta 0:02:40
     ------- ----------------------------- 19.9/101.7 MB 511.9 kB/s eta 0:02:40
     ------- ----------------------------- 19.9/101.7 MB 509.5 kB/s eta 0:02:41
     ------- ----------------------------- 19.9/101.7 MB 509.5 kB/s eta 0:02:41
     ------- ----------------------------- 20.0/101.7 MB 509.1 kB/s eta 0:02:41
     ------- ----------------------------- 20.0/101.7 MB 508.3 kB/s eta 0:02:41
     ------- ----------------------------- 20.0/101.7 MB 507.5 kB/s eta 0:02:41

In [30]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_curve,roc_auc_score

In [2]:
credit_details=pd.read_csv(filepath_or_buffer="credit_card_clean.csv")
credit_details

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

#### DATA UNDERSTANDING

In [3]:
credit_details.shape

(30000, 25)

In [4]:
credit_details.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [5]:
credit_details.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [6]:
credit_details.describe()

,ID,LIMIT_BAL,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,-0.291100,51223.330900,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,9.217904,1.123802,1.197186,1.196868,1.169139,1.133187,1.149988,73635.860576,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-165580.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3558.750000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22381.500000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67091.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,964511.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

####  DATA PREPARATION

##### DATA CLEANING

In [7]:
del credit_details["ID"]

In [8]:
credit_details

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,female,university,married,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,female,university,single,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,female,university,single,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,female,university,married,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,male,university,married,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,male,highschool,married,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,male,highschool,single,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,male,university,single,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,male,highschool,married,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,male,university,married,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [9]:
le=LabelEncoder()
credit_details["SEX"]=le.fit_transform(credit_details["SEX"])
credit_details["EDUCATION"]=le.fit_transform(credit_details["EDUCATION"])
credit_details["MARRIAGE"]=le.fit_transform(credit_details["MARRIAGE"])

In [10]:
credit_details.dtypes

LIMIT_BAL    float64
SEX            int64
EDUCATION      int64
MARRIAGE       int64
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

##### DATA SEGMENTATION

In [11]:
x=credit_details.drop(labels="DEFAULT",axis=1)
x

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,0,3,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,0,3,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,0,3,0,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,3,0,46,0,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [12]:
y=credit_details["DEFAULT"]
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: DEFAULT, Length: 30000, dtype: int64

#### MODEL BUILDING

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=25,shuffle=True,stratify=y)
x_train,x_test,y_train,y_test

(       LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
 1910    360000.0    1          0         0   38     -1     -1     -1     -1
 20739   240000.0    1          0         2   30     -1      0      0      0
 23904    20000.0    1          3         2   22      1      2      2      2
 8259     60000.0    0          3         2   23      0      0      0      0
 1937    360000.0    0          3         2   27      0      0      0      0
 ...          ...  ...        ...       ...  ...    ...    ...    ...    ...
 24545   390000.0    1          0         2   32     -1     -1     -1     -1
 22655   400000.0    0          3         0   39     -1      2     -1     -1
 22732   500000.0    0          3         0   38      0      0      0      0
 13673    30000.0    0          3         2   22      0      0      0      0
 194      50000.0    1          3         0   36      0      0      0      0

        PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
 1910      -1  ...      390.0      390.0      390.0      390.0       0.0
 20739      0  ...   186450.0   190523.0   194405.0   182630.0    6581.0
 23904      0  ...    16899.0    16335.0    16509.0    17590.0       0.0
 8259       0  ...    50243.0    15092.0    12037.0    10000.0    2351.0
 1937       0  ...   248969.0   253896.0   259403.0   264352.0   10381.0
 ...      ...  ...        ...        ...        ...        ...       ...
 24545     -1  ...    20868.0    14411.0    18969.0     8637.0   13000.0
 22655     -1  ...     5299.0     8841.0    18612.0     6115.0      31.0
 22732      0  ...    26741.0    27854.0    30961.0    54017.0    7000.0
 13673      0  ...    27758.0    22720.0    19136.0    14452.0    1600.0
 194       -1  ...    18250.0      -14.0       72.0      658.0    2000.0

        PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
 1910      390.0     390.0     390.0     390.0     390.0
 20739    6881.0    7181.0    7281.0    6638.0    6881.0
 23904    3132.0       0.0     742.0    1501.0       0.0
 8259     1237.0     422.0     528.0    2000.0    5000.0
 1937     9036.0    9066.0    9576.0    9426.0    9435.0
 ...         ...       ...       ...       ...       ...
 24545   20971.0   14487.0   19020.0      43.0   14753.0
 22655    5316.0    8858.0   18769.0    6115.0   11000.0
 22732    7000.0    2000.0    5000.0   25002.0    3000.0
 13673    2000.0    2000.0     614.0     924.0       0.0
 194      1000.0    2000.0     500.0    1000.0   20011.0

 [24000 rows x 23 columns],
        LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
 10763   210000.0    0          0         2   39     -2     -2     -2     -2
 10178   120000.0    1          0         2   34      1     -1     -1     -2
 17920    50000.0    1          3         2   25      0      0      0      0
 5092    520000.0    1          3         2   32      0      0      0      0
 23733    60000.0    0          1         0   60      0      0      0      0
 ...          ...  ...        ...       ...  ...    ...    ...    ...    ...
 9761    360000.0    1          3         0   33      1      2      2      7
 25796   200000.0    0          3         2   38     -2     -2     -2     -2
 11619    50000.0    1          3         0   49      0      0      0     -1
 18455   280000.0    0          3         2   26      0      0      0      0
 28731   240000.0    0          3         0   35     -1      2     -1     -1

        PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
 10763     -2  ...        0.0        0.0        0.0        0.0       0.0
 10178     -1  ...     -117.0     -513.0     1091.0      545.0    1000.0
 17920      0  ...    34836.0    18488.0    19716.0    17932.0    1795.0
 5092       0  ...     7894.0     6426.0     4045.0     1806.0    1222.0
 23733      0  ...    56594.0    57097.0    56854.0    58325.0    2810.0
 ...      ...  ...        ...        ...        ...        ...       ...
 9761       6  ...   383030.0   377145.0   370850.0   364365.0   14906.0
 25796     -2  ...     3000.0     3000.0     3000.0     3000.0    3000.0
 11619     -1  ...     6701.0     3581.0        0.0     6000.0    1158.0
 18455      0  ...    28111.0    29138.0    29852.0    30717.0    1800.0
 28731     -1  ...      264.0      264.0      264.0      414.0       0.0

        PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
 10763       0.0       0.0       0.0       0.0       0.0
 10178       0.0       0.0    2000.0       0.0     550.0
 17920    1660.0    1272.0    1500.0     644.0     704.0
 5092     1200.0     505.0     502.0     100.0  216338.0
 23733    2648.0    2050.0    2084.0    2437.0    1968.0
 ...         ...       ...       ...       ...       ...
 9761    97225.0       0.0       0.0       0.0       0.0
 25796    3000.0    3000.0    3000.0    3000.0    3000.0
 11619    1010.0    3581.0       0.0    6000.0    3261.0
 18455    1800.0    1800.0    1500.0    1500.0    1500.0
 28731     264.0     264.0     264.0     414.0     264.0

 [6000 rows x 23 columns],
 1910     1
 20739    0
 23904    1
 8259     1
 1937     1
         ..
 24545    0
 22655    0
 22732    0
 13673    1
 194      0
 Name: DEFAULT, Length: 24000, dtype: int64,
 10763    0
 10178    0
 17920    1
 5092     0
 23733    0
         ..
 9761     0
 25796    0
 11619    0
 18455    0
 28731    1
 Name: DEFAULT, Length: 6000, dtype: int64)

In [14]:
x_train.shape,x_test.shape

((24000, 23), (6000, 23))

In [15]:
y_train.shape,y_test.shape

((24000,), (6000,))

#### MODEL TRAINING

In [16]:
adb_classifier=AdaBoostClassifier()
gb_classifier=GradientBoostingClassifier()
xgb_classifier=XGBClassifier()
lgm_classifier=LGBMClassifier()

In [17]:
%%time
adb_classifier.fit(x_train,y_train)

CPU times: total: 3.44 s
Wall time: 3.75 s

AdaBoostClassifier()

In [18]:
%%time
gb_classifier.fit(x_train,y_train)

CPU times: total: 15.1 s
Wall time: 15.7 s

GradientBoostingClassifier()

In [19]:
%%time
xgb_classifier.fit(x_train,y_train)

CPU times: total: 3.45 s
Wall time: 573 ms

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [20]:
%%time
lgm_classifier.fit(x_train,y_train)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002858 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3259
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221208 -> initscore=-1.258639
[LightGBM] [Info] Start training from score -1.258639
CPU times: total: 1.84 s
Wall time: 4.23 s

LGBMClassifier()

#### MODEL TESTING

In [21]:
y_pred_adb=adb_classifier.predict(x_test)
y_pred_gb=gb_classifier.predict(x_test)
y_pred_xgb=xgb_classifier.predict(x_test)
y_pred_lgb=lgm_classifier.predict(x_test)

#### MODEL EVALUATION

###### ADBOOSTING

In [26]:
accuracy_score(y_test,y_pred_adb)

0.819

In [27]:
confusion_matrix(y_test,y_pred_adb)

array([[4463,  210],
       [ 876,  451]])

In [29]:
print(classification_report(y_test,y_pred_adb))

              precision    recall  f1-score   support

           0       0.84      0.96      0.89      4673
           1       0.68      0.34      0.45      1327

    accuracy                           0.82      6000
   macro avg       0.76      0.65      0.67      6000
weighted avg       0.80      0.82      0.79      6000

###### GRADIENT BOOSTING

In [38]:
accuracy_score(y_test,y_pred_gb)

0.821

In [39]:
confusion_matrix(y_test,y_pred_gb)

array([[4437,  236],
       [ 838,  489]])

In [40]:
print(classification_report(y_test,y_pred_gb))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.67      0.37      0.48      1327

    accuracy                           0.82      6000
   macro avg       0.76      0.66      0.68      6000
weighted avg       0.80      0.82      0.80      6000

###### EXTREMEGRADIENT BOOSTING

In [41]:
accuracy_score(y_test,y_pred_xgb)

0.814

In [42]:
confusion_matrix(y_test,y_pred_xgb)

array([[4372,  301],
       [ 815,  512]])

In [43]:
print(classification_report(y_test,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89      4673
           1       0.63      0.39      0.48      1327

    accuracy                           0.81      6000
   macro avg       0.74      0.66      0.68      6000
weighted avg       0.80      0.81      0.80      6000

###### LIGHT GRADIENT BOOSTING

In [46]:
round(accuracy_score(y_test,y_pred_lgb),ndigits=4)

0.8193

In [47]:
confusion_matrix(y_test,y_pred_lgb)

array([[4417,  256],
       [ 828,  499]])

In [48]:
print(classification_report(y_test,y_pred_lgb))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.66      0.38      0.48      1327

    accuracy                           0.82      6000
   macro avg       0.75      0.66      0.69      6000
weighted avg       0.80      0.82      0.80      6000

In [53]:
adb_feature_imp=adb_classifier.feature_importances_
gb_feature_imp=gb_classifier.feature_importances_
xgb_feature_imp=xgb_classifier.feature_importances_
lgb_feature_imp=lgm_classifier.feature_importances_

In [58]:
feature_important_data=pd.DataFrame(data={"feature":x.columns,
                                          "Adb_feature":adb_feature_imp,
                                          "Gb_feature":gb_feature_imp,
                                          "Xgb_featue":xgb_feature_imp,
                                          "Lgb_feature":lgb_feature_imp})
feature_important_data

      feature  Adb_feature  Gb_feature  Xgb_featue  Lgb_feature
0   LIMIT_BAL     0.052118    0.029976    0.025547          222
1         SEX     0.016852    0.004031    0.019097           40
2   EDUCATION     0.000000    0.003095    0.018161           63
3    MARRIAGE     0.019567    0.002943    0.020167           38
4         AGE     0.000000    0.006550    0.016818          210
5       PAY_1     0.586210    0.638531    0.393134          106
6       PAY_2     0.000000    0.068779    0.096704           45
7       PAY_3     0.053676    0.035435    0.052028           42
8       PAY_4     0.000000    0.021259    0.039279           47
9       PAY_5     0.024156    0.014288    0.033159           38
10      PAY_6     0.028016    0.019168    0.039349           57
11  BILL_AMT1     0.009623    0.034100    0.023965          249
12  BILL_AMT2     0.013855    0.007836    0.020930          178
13  BILL_AMT3     0.000000    0.007562    0.018072          143
14  BILL_AMT4     0.000000    0.005877    0.019070          134
15  BILL_AMT5     0.000000    0.006291    0.017633          138
16  BILL_AMT6     0.000000    0.007574    0.019896          141
17   PAY_AMT1     0.089017    0.019244    0.021945          171
18   PAY_AMT2     0.045537    0.017886    0.021732          200
19   PAY_AMT3     0.023537    0.022681    0.023853          201
20   PAY_AMT4     0.026024    0.012205    0.021790          177
21   PAY_AMT5     0.005383    0.007274    0.018363          174
22   PAY_AMT6     0.006428    0.007417    0.019308          186

### THE END

In [ ]:
======================================================================================================================================================