## KNN Technique

#### BUSINESS UNDERSTANDING

In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings("ignore")
from matplotlib import pyplot as plt

In [2]:
fav_wine=datasets.load_wine()
wine_dataset=pd.DataFrame(data=fav_wine.data,columns=fav_wine.feature_names)
wine_dataset["target"]=fav_wine.target
wine_dataset

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

#### DATA UNDERSTANDING

In [3]:
wine_dataset.dtypes

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_wines    float64
proline                         float64
target                            int64
dtype: object

In [4]:
wine_dataset.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [5]:
wine_dataset.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

#### DATA PREPARATION

In [6]:
x=wine_dataset.drop(labels="target",axis=1)
y=wine_dataset["target"]
x

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [7]:
y

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64

#### MODEL BUILDING

In [8]:
stand_scaler=StandardScaler()
stand_X=stand_scaler.fit_transform(x)

In [9]:
x_train,x_test,y_train,y_test=train_test_split(stand_X,y,test_size=0.20,random_state=25,shuffle=True,stratify=y)
x_train,x_test,y_train,y_test

(array([[-0.92721209,  1.38567923, -0.60867587, ..., -1.34888482,
         -0.86397064,  0.34426524],
        [-0.34663756, -0.47248348, -0.60867587, ...,  0.88865792,
          0.74621417, -0.10474838],
        [ 1.3086175 , -0.63406285, -0.3162486 , ...,  0.58154421,
          1.55130658,  0.10542821],
        ...,
        [-0.6060432 , -0.54429654, -1.41285087, ...,  0.36217728,
          1.35356458, -0.23849711],
        [ 0.85156946,  0.82912808,  0.63414004, ...,  0.01119018,
         -1.11821035, -0.21302116],
        [-1.66837107, -0.59815632,  0.92656731, ...,  1.76612566,
          0.84508517, -0.58879142]], shape=(142, 13)),
 array([[-1.53249192e+00,  3.08483453e-01,  2.02316959e+00,
          1.51660791e-01,  2.28785042e-01, -8.73450731e-01,
          7.33234123e-04,  1.91893483e+00, -9.47700337e-01,
         -5.44211919e-01,  1.19577163e+00, -1.57749231e-01,
         -4.45489206e-01],
        [ 6.09998823e-02, -5.44296535e-01, -1.19353041e+00,
         -2.13050515e+00, -5.43561704e-01,  6.80810871e-01,
          1.24565197e+00, -1.54592178e+00,  2.31117614e+00,
          9.26526023e-01,  7.13164373e-01,  4.21352323e-01,
          1.28369089e+00],
        [ 3.32758175e-01,  1.74474449e+00, -3.89355414e-01,
          1.51660791e-01,  1.42241183e+00, -1.12982378e+00,
         -1.34458217e+00,  5.49107795e-01, -4.22075098e-01,
          2.22423597e+00, -1.61212515e+00, -1.48544548e+00,
          2.80575367e-01],
        [ 7.15690314e-01, -6.07132956e-01, -2.38213228e-02,
         -1.18595702e-01,  4.39425064e-01,  9.05137288e-01,
          1.16533463e+00, -1.14303148e+00,  6.29175380e-01,
          7.96755028e-01,  5.81544212e-01,  3.78979039e-01,
          2.44603111e+00],
        [-1.71778167e+00, -8.85408531e-01,  1.21899459e+00,
          1.51660791e-01, -4.03135023e-01,  7.12857502e-01,
          8.94263617e-01, -5.78985054e-01,  1.57530081e+00,
         -1.04166740e+00,  1.11901785e-02,  9.15707308e-01,
         -2.13021163e-01],
        [-1.86053111e-01, -6.60992744e-01,  5.61033223e-01,
         -5.08966192e-01, -3.32921683e-01,  2.96251299e-01,
          3.42081920e-01, -8.20719236e-01, -2.29345844e-01,
         -4.87977821e-01,  5.81544212e-01,  1.43831115e+00,
          8.53784240e-01],
        [-7.17217046e-01,  1.91787244e-01, -3.52802005e-01,
          7.52230776e-01, -6.83988386e-01, -9.85613939e-01,
         -1.90020443e-01,  2.40240319e+00, -2.99429209e-01,
         -1.02003890e+00, -4.27543693e-01,  9.72205021e-01,
         -1.37536138e+00],
        [ 9.13332708e-01, -5.98156324e-01, -4.25908823e-01,
         -9.29365181e-01,  1.28198515e+00,  4.88531085e-01,
          8.74184283e-01, -1.22360954e+00,  5.09876168e-02,
          3.42556546e-01, -1.64303370e-01,  8.30960739e-01,
          9.97086458e-01],
        [ 6.09998823e-02, -5.08390010e-01, -9.74209960e-01,
         -7.49194186e-01,  5.09638405e-01,  1.12946370e+00,
          9.74580955e-01, -6.59563114e-01,  7.69342110e-01,
         -7.82513996e-03, -3.39796919e-01,  1.04282716e+00,
          4.39800054e-01],
        [-7.04864396e-01, -7.23829165e-01, -2.79695187e-01,
          6.02088279e-01, -9.64841748e-01,  7.12857502e-01,
          1.12517596e+00,  2.26795553e-01,  3.13800236e-01,
         -4.83652121e-01, -1.17339127e+00,  3.22481326e-01,
         -1.25753511e+00],
        [-1.47072867e+00, -1.94207909e-01,  1.36520822e+00,
          6.02088279e-01,  2.40539860e+00, -1.11380046e+00,
         -1.04339216e+00, -1.78765596e+00, -5.41374310e-02,
         -1.10655290e+00, -3.26832086e-02, -4.96735507e-01,
         -3.88168318e-01],
        [-7.78980294e-01, -1.13675421e+00, -9.74209960e-01,
         -2.98766697e-01, -8.24415067e-01,  1.96267611e+00,
          1.72755600e+00, -9.81875357e-01,  6.29175380e-01,
         -2.41412931e-01,  3.62177276e-01,  2.23610329e-01,
         -2.76711037e-01],
        [ 9.00980058e-01,  1.81655754e+00, -3.89355414e-01,
          9.02373272e-01, -8.24415067e-01, -1.62654656e+00,
         -1.56545485e+00,  1.27431034e+00, -7.72491924e-01,
          6.75635433e-01, -7.78530790e-01, -1.21708134e+00,
         -7.22540161e-01],
        [ 1.39508604e+00,  1.58316512e+00,  1.36520822e+00,
          1.50294326e+00, -2.62708342e-01, -3.92751267e-01,
         -1.27430450e+00,  1.59662258e+00, -4.22075098e-01,
          1.79166599e+00, -1.52437837e+00, -1.42894777e+00,
         -5.95160411e-01],
        [-1.28543893e+00, -1.11880095e+00, -2.43141777e-01,
          4.51945783e-01,  8.83583612e-02,  1.73834969e+00,
          1.11169574e-01, -1.86823402e+00,  1.03550141e-01,
         -7.99428209e-01,  1.42810340e-01,  7.32089742e-01,
          4.42984548e-01],
        [ 1.96879028e-01,  1.10740365e+00, -7.91442914e-01,
          4.51945783e-01,  1.58571702e-01, -1.27403362e+00,
         -1.48513751e+00,  5.49107795e-01, -5.09679305e-01,
         -4.57697922e-01, -1.56825176e+00, -1.31595234e+00,
          2.64652898e-01],
        [-2.23111060e-01,  9.27871023e-01, -2.43141777e-01,
          1.51829490e-03, -8.24415067e-01, -1.30608025e+00,
         -1.37470118e+00,  3.07373613e-01, -1.08786707e+00,
          2.25019017e+00, -1.04177111e+00, -1.21708134e+00,
         -1.97098694e-01],
        [-1.48995162e-01,  5.86759028e-01,  1.22392314e-01,
          1.51660791e-01,  2.98998383e-01, -1.59449993e+00,
         -8.12479811e-01, -9.81875357e-01, -1.33315885e+00,
          1.47900054e-01, -9.54024339e-01, -1.68318747e+00,
         -6.90695223e-01],
        [-1.31160156e-02, -5.98156324e-01,  8.53460496e-01,
          3.15451071e+00,  2.75646531e+00,  1.61016317e+00,
          8.64144615e-01, -1.22360954e+00,  6.46696221e-01,
         -7.38868411e-01,  1.54675873e+00,  1.25469358e+00,
          7.58249428e-01],
        [ 1.06156450e+00, -7.41782427e-01,  1.10933436e+00,
          1.65308575e+00, -9.64841748e-01,  1.04934713e+00,
          8.34025614e-01, -1.22360954e+00,  4.89008649e-01,
         -7.25891312e-01,  1.76612566e+00,  7.74463027e-01,
         -1.07283447e+00],
        [ 8.76274759e-01,  2.97454300e+00,  3.05159359e-01,
          3.01803287e-01, -3.32921683e-01, -9.85613939e-01,
         -1.42489951e+00,  1.27431034e+00, -9.30179496e-01,
          1.14281101e+00, -1.39275821e+00, -1.23120577e+00,
         -2.19515383e-02],
        [ 7.77453562e-01, -4.72483484e-01,  1.21899459e+00,
         -6.89137187e-01,  8.60705108e-01,  8.89113972e-01,
          8.84223950e-01, -4.98406993e-01, -2.29345844e-01,
          9.69783022e-01,  1.41513857e+00,  3.78979039e-01,
          1.79320989e+00],
        [ 6.09998823e-02, -2.57044329e-01,  3.11977186e+00,
          1.65308575e+00,  1.70326520e+00,  5.36601031e-01,
          6.53311604e-01,  8.71420038e-01,  5.76612856e-01,
         -6.39377315e-01,  7.57037760e-01,  8.30960739e-01,
          2.64652898e-01],
        [ 2.25977152e+00, -6.25086219e-01, -7.18336096e-01,
         -1.65004916e+00, -1.92495001e-01,  8.08997395e-01,
          9.54501620e-01, -5.78985054e-01,  6.81737904e-01,
          6.13860573e-02,  5.37670824e-01,  3.36605754e-01,
          9.49319052e-01],
        [-1.73700461e-01, -8.85408531e-01, -1.70034959e-01,
         -4.48909194e-01,  1.56283851e+00, -1.25801030e+00,
         -7.82360809e-01, -1.22360954e+00, -1.14042959e+00,
         -4.14440924e-01, -8.66277565e-01, -1.86680504e+00,
         -3.72245850e-01],
        [ 1.07391715e+00, -3.91693801e-01,  1.58452868e+00,
         -2.85102043e-02,  5.09638405e-01,  1.04934713e+00,
          9.44461953e-01,  6.56394314e-02,  2.96279395e-01,
         -2.41412931e-01,  1.28351841e+00,  1.11344930e+00,
          5.35334866e-01],
        [ 8.88627409e-01, -8.13595479e-01,  4.87926405e-01,
         -8.39279684e-01,  5.79851746e-01,  1.77039632e+00,
          1.64723866e+00, -1.38476566e+00,  7.86862952e-01,
          7.53498030e-01, -2.95923532e-01,  3.64854610e-01,
          1.71359755e+00],
        [ 7.15690314e-01,  2.18717138e-01,  1.18244118e+00,
          1.50294326e+00,  3.69211724e-01, -1.19391704e+00,
         -1.19398717e+00,  2.26795553e-01, -8.91791136e-02,
          1.55807820e+00, -9.54024339e-01, -1.14645920e+00,
          9.89339909e-03],
        [-1.14955978e+00, -1.58301383e-01, -7.18336096e-01,
          4.51945783e-01, -1.03505509e+00,  4.88531085e-01,
          6.23192602e-01,  6.56394314e-02, -4.22075098e-01,
         -9.94084701e-01, -4.27543693e-01,  9.43956165e-01,
         -1.17473827e+00],
        [-1.90307141e+00,  1.26000639e+00, -1.99770541e+00,
          1.51829490e-03,  5.09638405e-01,  1.41788338e+00,
          5.52914931e-01, -9.81875357e-01,  3.48507251e+00,
         -9.33524903e-01, -9.10150952e-01,  2.80108041e-01,
         -5.88791424e-01],
        [ 4.80989970e-01, -5.08390010e-01,  9.26567314e-01,
         -1.01945068e+00, -4.73348364e-01,  8.89113972e-01,
          9.14342951e-01, -1.76094750e-01, -2.46866685e-01,
         -1.11641936e-01, -1.64303370e-01,  8.59209596e-01,
          1.42699311e+00],
        [-2.35463709e-01, -2.36519110e-02,  1.22392314e-01,
          1.35280076e+00, -1.22281661e-01, -1.83484966e+00,
         -9.42995485e-01, -7.40141175e-01, -1.33315885e+00,
          2.77671049e-01, -1.30501144e+00, -1.76793404e+00,
         -5.95160411e-01],
        [ 2.95700226e-01,  2.27693770e-01,  1.84040254e+00,
          4.51945783e-01,  1.28198515e+00,  8.08997395e-01,
          6.63351271e-01,  2.26795553e-01,  4.01404443e-01,
         -3.19275528e-01,  3.62177276e-01,  4.49601179e-01,
         -3.78740070e-02],
        [-1.77954492e+00, -2.57044329e-01,  3.15632527e+00,
          2.70408323e+00,  1.35219849e+00,  1.41788338e+00,
          3.06283174e+00,  8.71420038e-01,  4.89008649e-01,
          4.07442044e-01, -1.20429983e-01,  1.52305772e+00,
         -8.97687316e-01],
        [ 6.09998823e-02,  1.36772596e+00, -1.70034959e-01,
          9.02373272e-01, -1.03505509e+00, -1.03368389e+00,
         -4.41012124e-01,  1.99951289e+00,  5.09876168e-02,
         -1.11641936e-01, -5.15290467e-01, -8.49846211e-01,
         -7.38462629e-01],
        [-1.18661773e+00,  1.76269775e+00,  4.92854954e-02,
          7.52230776e-01, -1.38612179e+00, -3.12634689e-01,
         -2.80377448e-01,  4.68529735e-01, -4.22075098e-01,
         -1.06329590e+00, -7.34657403e-01, -5.88782342e-02,
         -5.31470536e-01]]),
 144    2
 81     1
 20     0
 153    2
 85     1
       ..
 64     1
 9      0
 104    1
 161    2
 87     1
 Name: target, Length: 142, dtype: int64,
 112    1
 50     0
 175    2
 31     0
 109    1
 23     0
 105    1
 54     0
 44     0
 126    1
 96     1
 98     1
 165    2
 177    2
 74     1
 145    2
 167    2
 131    2
 73     1
 71     1
 173    2
 15     0
 25     0
 8      0
 130    2
 28     0
 58     0
 168    2
 125    1
 110    1
 26     0
 132    2
 4      0
 121    1
 83     1
 129    1
 Name: target, dtype: int64)

In [10]:
x_train.shape,x_test.shape

((142, 13), (36, 13))

In [11]:
y_train.shape,y_test.shape

((142,), (36,))

#### MODEL TRAINING

In [12]:
knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

#### MODEL TESTING

In [13]:
y_pred_train=knn_model.predict(x_train)
y_pred_train

array([2, 1, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 2, 2, 0, 1, 1, 0, 2, 2, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 1, 0, 1, 2, 0, 1,
       0, 2, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       1, 0, 2, 1, 2, 0, 2, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 0,
       0, 0, 1, 1, 2, 1, 1, 0, 2, 0, 2, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2,
       0, 2, 0, 0, 0, 1, 0, 1, 2, 1])

In [14]:
y_pred_test=knn_model.predict(x_test)
y_pred_test

array([1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 2, 2, 2, 0, 0, 2, 0,
       0, 0, 2, 0, 0, 2, 1, 1, 0, 2, 0, 1, 2, 1])

#### MODEL EVALUATION

### K=3

In [15]:
knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(x_train,y_train)
y_pred_train=knn_model.predict(x_train)
print( 'Training_accuracy:', accuracy_score(y_train,y_pred_train))

Training_accuracy: 0.9859154929577465

### K=5

In [16]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train,y_train)
y_pred_train=knn_model.predict(x_train)
print( 'Training_accuracy:', accuracy_score(y_train,y_pred_train))

Training_accuracy: 0.9929577464788732

### K=9

In [17]:
knn_model=KNeighborsClassifier(n_neighbors=9)
knn_model.fit(x_train,y_train)
y_pred_train=knn_model.predict(x_train)
print( 'Training_accuracy:', accuracy_score(y_train,y_pred_train))

Training_accuracy: 0.9859154929577465

### K=11

In [18]:
knn_model=KNeighborsClassifier(n_neighbors=11)
knn_model.fit(x_train,y_train)
y_pred_train=knn_model.predict(x_train)
print( 'Training_accuracy:', accuracy_score(y_train,y_pred_train))

Training_accuracy: 0.9859154929577465

In [19]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        47
           1       1.00      0.96      0.98        57
           2       0.97      1.00      0.99        38

    accuracy                           0.99       142
   macro avg       0.98      0.99      0.99       142
weighted avg       0.99      0.99      0.99       142

In [20]:
confusion_matrix(y_train,y_pred_train)

array([[47,  0,  0],
       [ 1, 55,  1],
       [ 0,  0, 38]])

###### TEST ACCURACY

#### K=11

In [29]:
knn_model=KNeighborsClassifier(n_neighbors=11)
knn_model.fit(x_train,y_train)
y_pred_test=knn_model.predict(x_test)
print( 'Testing_accuracy:', round(accuracy_score(y_test,y_pred_test),ndigits=4))

print(classification_report(y_train,y_pred_train))
print("confusion_matrix:",confusion_matrix(y_test,y_pred_test))

Testing_accuracy: 0.9444
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        47
           1       1.00      0.96      0.98        57
           2       0.97      1.00      0.99        38

    accuracy                           0.99       142
   macro avg       0.98      0.99      0.99       142
weighted avg       0.99      0.99      0.99       142

confusion_matrix: [[12  0  0]
 [ 1 12  1]
 [ 0  0 10]]

#### K=5

In [23]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train,y_train)
y_pred_test=knn_model.predict(x_test)
print( 'Testing_accuracy:', accuracy_score(y_test,y_pred_test))

print(classification_report(y_train,y_pred_train))
print("confusion_matrix:",confusion_matrix(y_test,y_pred_test))

Testing_accuracy: 0.9444444444444444
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        47
           1       1.00      0.96      0.98        57
           2       0.97      1.00      0.99        38

    accuracy                           0.99       142
   macro avg       0.98      0.99      0.99       142
weighted avg       0.99      0.99      0.99       142

confusion_matrix: [[12  0  0]
 [ 1 12  1]
 [ 0  0 10]]

#### K=9

In [22]:
knn_model=KNeighborsClassifier(n_neighbors=9)
knn_model.fit(x_train,y_train)
y_pred_test=knn_model.predict(x_test)
print( 'Testing_accuracy:', accuracy_score(y_test,y_pred_test))

print(classification_report(y_train,y_pred_train))
print("confusion_matrix:",confusion_matrix(y_test,y_pred_test))

Testing_accuracy: 0.9444444444444444
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        47
           1       1.00      0.96      0.98        57
           2       0.97      1.00      0.99        38

    accuracy                           0.99       142
   macro avg       0.98      0.99      0.99       142
weighted avg       0.99      0.99      0.99       142

confusion_matrix: [[12  0  0]
 [ 1 12  1]
 [ 0  0 10]]

#### KFOLD

In [30]:
from sklearn.model_selection import cross_val_score,KFold

In [42]:
k_fold=KFold(n_splits=5,shuffle=True,random_state=23)
cross_score=cross_val_score(estimator=knn_model,X=stand_X,y=y,cv=k_fold)
print(cross_score)
print("Overall accuracy:",cross_score.mean().round(4))
print("Overall standard devation:",cross_score.std().round(4))

[1.         0.88888889 1.         0.94285714 0.94285714]
Overall accuracy: 0.9549
Overall standard devation: 0.0418

##### INTREPRETITION 
1. FIRST FOLD:1.00
2. SECOND FOLD:0.88
3. THIRD FOLD:1.00
4. FOURTH FOLD:0.942
5. FIFTH FOLD:0.942

### NOTES
1.On average,your KNN model correctly classifies about *95 out of every 100wine sample*.
2.SD:Tells you how much the accuracy changes from one fold to another, small SD:The model performs consistently on every fold.
                                                                       large SD:The model perform changes a lot depending on the data split.
3.The SD is about 0.043%(This is low,which is good).

#### THE END

In [ ]:
=======================================================================================================================================================